seung-lab/neuroglancer

python/neuroglancer/downsample.py
python/neuroglancer/ingest/volumes/gcloudvolume.py
python/neuroglancer/volume.py

… new segmentation downsampling code.
Also made downsampling code able to handle more factors like (4,4,1) and (8,8,1) via recursion

GCloudVolume Update & Segmentation Downsampling Enhancement

---

python/neuroglancer/chunks.py
python/neuroglancer/downsample.py
python/neuroglancer/downsample_scales.py
python/neuroglancer/ingest/lib.py
python/neuroglancer/ingest/super_downsample.py
python/neuroglancer/ingest/volumes/gcloudvolume.py

- Superdownsample in blocks to avoid excessive memory pressure
- Bug fixes for GCloudVolume offset support
- Some refactoring
- Introduced downsample_scales for generating a stack of downsampled images in a z stack without downsampling in Z. This is to help Tommy with alignment.

Superdownsample in Blocks

---

python/Dockerfile
python/neuroglancer/ingest/lib.py
python/neuroglancer/ingest/volumes/gcloudvolume.py

Just Gcloud stuff, I haven't added new Storage support yet

Improvements to GCloudVolume and lib.py

---

python/neuroglancer/pipeline/storage.py
python/test/test_storage.py

Note: I changed Queue to use block=True instead of waiting for it to burn down so that way all threads are maximally utilized.

feat(storage): get_files implements multithreaded gets

---

python/neuroglancer/graph_server.py
python/neuroglancer/ingest/lib.py
python/neuroglancer/ingest/super_downsample.py
python/neuroglancer/ingest/volumes/volumes.py

Modifying a few print statements so that python3 won't complain

2to3 print statements

---

python/neuroglancer/pipeline/storage.py
python/neuroglancer/pipeline/task_execution.py
python/neuroglancer/pipeline/task_queue.py
python/test/test_taskqueue.py

We now can insert tasks about 28x faster.

Threaded Cloud Task Insertion

---

python/neuroglancer/pipeline/storage.py

When a file doesn't exist we sometimes assume it is an empty file.
But we need to be careful of interpreting other types of exceptions
as a non existent file.

fix(storage): More explicit exception handling.

---

python/neuroglancer/pipeline/task_queue.py

Deletion can now handle task id's or task.

fix(task_queue): fixes task deletion.

---

python/neuroglancer/downsample.py
python/neuroglancer/pipeline/task_creation.py
python/neuroglancer/pipeline/tasks.py
python/test/test_precomputed.py
python/test/test_tasks.py

Adds specific tests to test downsampling of images,
segmentation and affinities.

fix(downsampling): Adds more test and fixes downsampling factor.

---

python/neuroglancer/pipeline/task_execution.py
python/neuroglancer/pipeline/task_queue.py
python/requirements.txt

task_execution takes an optional parameter,
the tasks tag.
This is useful to make a kubernetes deployment
which only executes a certain kind of tasks.

feat(task_execution): tag can be specified in cli argument.

---

python/neuroglancer/pipeline/storage.py
python/test/test_storage.py

Please review after merging #75 
Should probably make this handle #78 as well.

Storage Uses ThreadedQueue

---

python/neuroglancer/pipeline/storage.py
python/test/test_storage.py

Mainly for cleaning up test files on gs and s3

Storage: Delete Files

---

python/README.md

Write down the instructions I followed to build the C++ extension module so I could start developing with the python objects in this repo.
Help resolve #128.

Update python dir README with getting started instructions

---

python/ext/third_party/mc/cMesher.cpp

If all voxels of a given chunk are part of the selected object (blood vessel or cell body agglomeration), then the result of marching cubes is empty. That caused the `get_mesh` function to crash when attempting to retrieve the (non-existing) triangles.
In such cases an empty mesh with 0 vertices is now returned.

(fix) Handling empty marching cubes results

---

python/neuroglancer/pipeline/scripts/validate_provenance.py

'removeme' data layers are used for testing and usually aren't
intended to be fully consistent with all the features of a data
layer.

feat(validate_provenance): remove 'removeme' paths from results

---

python/neuroglancer/pipeline/storage.py
python/requirements.txt
python/test/test_storage.py

See #91 
I added the functionality recommended here by [AWS]( https://www.awsarchitectureblog.com/2015/03/backoff.html) to the tenacity library in this PR: 
https://github.com/jd/tenacity/pull/70

 feat(Storage): added retry logic recommended on AWS blog

---

python/neuroglancer/pipeline/scripts/ngmesh2obj.py

Now produces a unifed mesh file instead of lots of mesh fragment files.
Also a major performance boost.

feat(ngmesh2obj): produce one file per mesh

---

python/neuroglancer/pipeline/kube.yml
python/neuroglancer/pipeline/task_execution.py
python/neuroglancer/pipeline/task_queue.py

set task lease time from environment variable

set task lease time

---

config/webpack_helpers.js
src/neuroglancer/chunk_manager/base.ts
src/neuroglancer/chunked_graph/backend.ts
src/neuroglancer/chunked_graph/frontend.ts
src/neuroglancer/datasource/precomputed/frontend.ts
src/neuroglancer/layer.ts
src/neuroglancer/mesh/backend.ts
src/neuroglancer/mesh/frontend.ts
src/neuroglancer/rendered_data_panel.ts
src/neuroglancer/segmentation_display_state/backend.ts
src/neuroglancer/segmentation_display_state/base.ts
src/neuroglancer/segmentation_display_state/frontend.ts
src/neuroglancer/segmentation_user_layer.ts
src/neuroglancer/shared_disjoint_sets.ts
src/neuroglancer/skeleton/backend.ts
src/neuroglancer/skeleton/frontend.ts
src/neuroglancer/sliceview/volume/frontend.ts
src/neuroglancer/sliceview/volume/segmentation_renderlayer.ts
src/neuroglancer/ui/default_input_event_bindings.ts
src/neuroglancer/util/disjoint_sets.spec.ts
src/neuroglancer/util/disjoint_sets.ts
src/neuroglancer/viewer.ts
src/neuroglancer/widget/chunked_graph_widget.css
src/neuroglancer/widget/chunked_graph_widget.ts
src/neuroglancer/widget/segment_set_widget.ts

* Two click Merge (key 'M') and Two click Split/Cut (key 'C') for segmentation layers with Chunked Graph Server
* Merge also works without graph server, using the equivalence classes of Neuroglancer. Cut not yet supported.
Warning: Neuroglancer equivalence classes now use the maximum ID as representative!

feat(chunkedgraph) Adding Chunked Graphserver, Merge+Split

---

src/neuroglancer/annotation/frontend.ts
src/neuroglancer/annotation/point_color_list.ts
src/neuroglancer/annotation/point_size_list.ts
src/neuroglancer/annotation/user_layer.ts
src/neuroglancer/widget/point_list_widget.ts

* Adjustable Color
* Adjustable Size
* Optional Perspective Scaling for 2D/3D view

feat(annotation): adjustable points

---

src/neuroglancer/util/uint64.spec.ts
src/neuroglancer/util/uint64.ts

fix(uint64) parsing works correctly if low part would be 2^32

---

src/neuroglancer/util/http_request.spec.ts
src/neuroglancer/util/http_request.ts

neuroglancer nolonger support s3:// link, add this protocol here.

Add s3 protocol

---

src/neuroglancer/segmentation_display_state/frontend.ts
src/neuroglancer/sliceview/volume/segmentation_renderlayer.ts

* In addition to highlighting the equivalence class itself, subtly decrease saturation for the underlying supervoxel, too.

feat(segmentation_render_layer): highlighting of equivalence components

---

package.json
src/neuroglancer/perspective_view/panel.ts
src/neuroglancer/webgl/offscreen.ts

Resolves #225
The receptive field is square, so the diagonals are more extensive. Would going circular be beneficial?

feat: larger and configurable receptive field for cursor in 3D

---

src/neuroglancer/ui/layer_side_panel.css

Added scrollbar to side panel to fix unreachable side panel segments bug

---

package.json

Can now run dev-server from fresh install

Upgraded Jasmine to 2.8.9 to fix compatibility with TypeScript

---

python/examples/example_action.py
python/neuroglancer/viewer_state.py
src/neuroglancer/layer_specification.ts
src/neuroglancer/util/http_request.spec.ts
src/neuroglancer/util/json.ts
src/neuroglancer/viewer.ts

Fixes this issue: https://github.com/seung-lab/neuroglancer/issues/228

Layer order now preserved on refresh or on load from URL or JSON server

---

src/neuroglancer/annotation/frontend_source.ts
src/neuroglancer/annotation/index.ts
src/neuroglancer/ui/annotations.ts

Changes to annotation list to avoid full refresh of the list
Create separate functions and signals for add/update/delete annotation and trigger signals accordingly
Create interface for common signals between AnnotationSource and MultiscaleAnnotationSource

update individual annotations

---

src/neuroglancer/segmentation_user_layer.ts

Links that don't use a graph server _and_ contained `segmentEquivalences` would not properly show their triangle meshes / skeletons.

fix(segmentation_user_layer): restore segment equivalences

---

package-lock.json
src/neuroglancer/annotation/annotation_layer_state.ts
src/neuroglancer/annotation/frontend_source.ts
src/neuroglancer/annotation/index.ts
src/neuroglancer/annotation/user_layer.css
src/neuroglancer/annotation/user_layer.ts
src/neuroglancer/ui/annotations.css
src/neuroglancer/ui/annotations.ts
src/neuroglancer/viewer.ts

Introduces tags to annotation layers that allow the user to tag a
selected annotation with a user-specified tag by hitting a shortcut. The
user can also cycle through annotations with the bracket keys, and
filter the annotations based on their tag.

Annotation shortcuts for tagging annotations

---

src/neuroglancer/ui/annotations.css
src/neuroglancer/ui/annotations.ts

Add button for annotation layers to download annotation coordinates, tags, description, and associated segment IDs to a csv file

feat: Add export annotations to csv button

---

src/neuroglancer/data_panel_layout.ts
src/neuroglancer/preferences/user_preferences.ts
src/neuroglancer/sliceview/backend.ts
src/neuroglancer/sliceview/frontend.ts
src/neuroglancer/ui/statistics.ts
src/neuroglancer/viewer.ts

* Add prefetched chunk statistics to the chunk statistics menu
* Make Sliceview Prefetching a Local Storage user setting, default: `false`

Add user setting: Sliceview prefetching (default: off)

---

python/neuroglancer/viewer_state.py

The neuroglancer python interface wasn't working with the new `segmentation_with_graph` layer type, resulting in errors when trying to programmatically generate neuroglancer states with it. This should fix that by adding a base segmentation class with all the machinery and subclassing it to set the `type` field as needed by precomputed and graphene-style segmentation sources.

Python support for segmentation_with_graph layers

---

src/neuroglancer/user_report/user_report.css
src/neuroglancer/user_report/user_report.ts
src/neuroglancer/viewer.ts

Removed email field, added disclaimer, link to previous issue, send URL disabled unless shorten server selected, auto shortens on form opening.

bug reporter (hotfix)

---

src/neuroglancer/whats_new/whats_new.ts

apparently page/file/dir in url is case sensitive

---

WHATS_NEW.md
src/neuroglancer/layer_panel.css

Fixed width

---

src/neuroglancer/perspective_view/panel.ts
src/neuroglancer/preferences/user_preferences.ts
src/neuroglancer/rendered_data_panel.ts
src/neuroglancer/util/mouse_drag.ts
src/neuroglancer/viewer.ts

Mousedrag and Shift + Mousedrag on perspective view only now implement pointer lock, pointer disappears and movement is unimpeded. Cursor restored upon mouseup

Feature: Free Rotation and Translation

---

WHATS_NEW.md
src/neuroglancer/widget/segment_set_widget.ts

Seun highlighthotfix

---

src/neuroglancer/annotation/line.ts
src/neuroglancer/webgl/shader_lib.ts

Requested for synapse proofreading. Shifts the color of each line annotation endpoint by 60°

Separate colors for line annotation start and endpoint

---

src/neuroglancer/ui/default_input_event_bindings.ts

Change clear segments shortcut to ctrl+shift+x

---

src/neuroglancer/ui/annotations.ts

Fix: Update annotation position on childUpdated

---

src/neuroglancer/datasource/graphene/backend.ts

Required for https://github.com/seung-lab/PyChunkedGraph/pull/160

fix(graphene): Send authenticated mesh manifest requests

---

src/neuroglancer/datasource/graphene/backend.ts
src/neuroglancer/datasource/graphene/base.ts
src/neuroglancer/datasource/graphene/frontend.ts
src/neuroglancer/sliceview/chunked_graph/backend.ts
src/neuroglancer/sliceview/chunked_graph/frontend.ts

First commit introduces API version verification while still maintaining support for PyChunkedGraph's legacy / V0 API
Second commit updates all endpoints to use the new V1 API.

feat(graphene): read supported API versions from endpoint + V1

---

src/neuroglancer/sliceview/chunked_graph/backend.ts
src/neuroglancer/sliceview/volume/segmentation_renderlayer.ts

rather than using the direct path link, use the path alias defined in tsconfig

fix imports for dependent projects

---

src/neuroglancer/ui/hiding_list.ts

Don't resize annotation panel when hiding it

---

src/neuroglancer/ui/annotations.ts

fix(annotations): CSV formatting for ellipsoid radii

---

WHATS_NEW.md
src/main_python.ts
src/neuroglancer/preferences/user_preferences.ts
src/neuroglancer/save_state/save_state.css
src/neuroglancer/save_state/save_state.ts
src/neuroglancer/status.ts
src/neuroglancer/ui/default_input_event_bindings.ts
src/neuroglancer/ui/default_viewer_setup.ts
src/neuroglancer/ui/url_hash_binding.ts
src/neuroglancer/viewer.ts

Seun save state

---

src/index.html
src/neuroglancer/viewer.ts

FDC #1 (Fallback and Damage Control)

---

src/neuroglancer/layer_specification.ts
src/neuroglancer/preferences/user_preferences.ts
src/neuroglancer/save_state/save_state.ts
src/neuroglancer/status.ts
src/neuroglancer/ui/graph_multicut.ts
src/neuroglancer/ui/url_hash_binding.ts
src/neuroglancer/viewer.ts

This patch fixes all problems. All of them ever. Every problem that has existed, exists, and will exist. This solves them all. Pack it up, we are done. Shows over folks.

Seun Save State Mac Patch

---

src/neuroglancer/authentication/frontend.ts

expose the auth token shared valua so that UI can respond to it changing

---

src/neuroglancer/viewer.ts

need for nue, minor 1 line change

toggle what's new via localstorage entry

---

src/neuroglancer/viewer.ts

disable whats new via local storage entry

---

src/neuroglancer/layer.ts
src/neuroglancer/layer_dialog.ts
src/neuroglancer/layer_panel.ts
src/neuroglancer/ui/annotations.ts

Set Annotation filename export to be name of layer

---

src/neuroglancer/ui/annotations.ts

Addressing #469, adds an option to filter for untagged annotations

Filter for untagged annotations

---

src/neuroglancer/save_state/save_state.ts

add private and public to all save state functions

---

WHATS_NEW.md
src/neuroglancer/ui/default_input_event_bindings.ts
src/neuroglancer/viewer.ts

Addresses #465, Backquote/Tilde key can be used to complete annotations.

Partial Solution for #465

---

src/neuroglancer/sliceview/chunked_graph/frontend.ts
src/neuroglancer/widget/find_path_widget.css
src/neuroglancer/widget/find_path_widget.ts

Pulling this missing functionality from the now deprecated akhilesh-graphene-sharded branch

add rough precision mode for find path tool

---

src/neuroglancer/viewer.ts

To allow flywire to adjust min side panel size

min side panel size argument

---

.travis.yml
appengine/frontend/app.yaml

Update travis to deployment v2 (beta) to fix gcloud crash

---

src/neuroglancer/ui/graph_multicut.ts

fix: enforce selection of both groups for multicut

---

src/neuroglancer/widget/minimizable_group.css

fix(minimizable-group): Chrome 92 flex-box fix

---

src/neuroglancer/sliceview/chunked_graph/frontend.ts
src/neuroglancer/status.ts
src/neuroglancer/ui/default_input_event_bindings.ts
src/neuroglancer/viewer.ts

fixed merge conflicts in https://github.com/seung-lab/neuroglancer/pull/592

Neuvue Feat: Adds new hotkey for removing status messages

---

src/neuroglancer/annotation/annotation_layer_view.ts
src/neuroglancer/save_state/save_state.ts
src/neuroglancer/user_report/user_report.ts
src/neuroglancer/util/br.ts

renamed to all lowercase; ghactiion doesnt like uppercase for some reason

this allows importCSV to utilize segment selection

---

.github/workflows/build.yml

also switched google cloud project from neuromancer-seung-import to seung-lab

updated github action to use Workload Identity Federation along with updates to other actions
