seung-lab/neuroglancer

- .gitignore
- devserver.sh
- src/neuroglancer/util/http_request.spec.ts
- src/neuroglancer/util/http_request.ts
Allow people to use glance://golden_v0/image instead of https://example.com/blob/golden_v0/image when specifying datasets
Also created Google app engine devserver start script
> glance:// protocol for authenticated gcloud datasets

- python/state.py
- src/neuroglancer/url_hash_state.ts
Connection seems to be re instatianted whenever there is a new message.
Even though making global variables is generally not a good practice,
just to keep this script as simple as possible we decided to put them
out there.
> fix(state_server)

- python/neuroglancer/ingest/tasks.py
- python/neuroglancer/ingest/volumes/precomputed.py
- python/test/test_precomputed.py
Precomputed now allows for non grid aligned slices read, which is
required for MeshTask to get the 1-pixel overlap.
Maybe we should add a flag to the constructor to dissable this
feature, given that if by mistake we get non-aligned there is
a big performance penalty.
Writting to non grid aligned slices is dissable, because task
processing should be idempotent. And we have no methods for
write sincronization between tasks.
> Support non-grid-aligned slices

- python/neuroglancer/pipeline/precomputed.py
- python/test/test_precomputed.py
`pr[0:64,0:64,0:64] = np.zeros(shape=(5,5,5,1))`
used to be legal because we were not checking sizes.
Numpy advance slicing was letting this happen:
```
In [1]: import numpy as np
In [2]: np.zeros(shape=(2,))[0:4]
Out[2]: array([ 0.,  0.])
```
This was causing corrupt chunks, which were not able
to be visualize in neuroglancer.
> fix(precomputed): __setitem__ didn't check shape size.

- python/neuroglancer/pipeline/secrets.py
- python/neuroglancer/pipeline/task_queue.py
- python/test/test_taskqueue.py
- TaskQueue.purge was relisting while threads were still deleting the last listing.
This leads to weird race conditions that is fixed with a simple wait.
- Added TaskQueue.wait as it allows for nice semantics like tq.delete().wait()
- Added support for TaskQueue.get, TaskQueue.get_task, and TaskQueue.enqueued
Note: Failing downsample test is fixed in PR #43 which is caused by a race condition.
> TaskQueue Purge Fix + TaskQueue.get Support

- python/neuroglancer/pipeline/precomputed.py
- python/neuroglancer/pipeline/storage.py
- python/neuroglancer/pipeline/task_creation.py
- python/neuroglancer/pipeline/tasks.py
- python/test/test_storage.py
- python/test/test_tasks.py
refractor(tasks): wait_until_queue_empty -> wait
To speed up file uploading and downloading Storage implements
asyncronous operations. When subsequent code depends on the
operations being performed wait() is required. wait() blocks
until all operations have being executed.
It renames wait_until_queue_empty() to the less verbose wait()
in the Storage class.
This commit also adds wait() to task which required it and were
neglecting it.
> refractor(storage): wait_until_queue_empty -> wait

- Dockerfile
- python/neuroglancer/pipeline/precomputed.py
- python/neuroglancer/pipeline/storage.py
- python/requirements.txt
The python library google-cloud doesn't set the header
`accept-encoding` when retriving objects from google
cloud storage.
The server decompresses the gzipped objects and send
them to the client. Making transfers way larger than
what they should be. For example for a segmentation which
has a size of 64mb is around 500kb compressed.
The library was forked in
https://github.com/tartavull/google-cloud-python
and modified to set the correct headers, and the
requirements file modified to use it. Solving:
https://github.com/seung-lab/neuroglancer/issues/65
Another bug was fixed, were objects were download twice.
> fix(GoogleCloudStorageInterface): downloads gzipped if available.

- python/.gitignore
- python/ext/src/endian.h
- python/ext/src/on_demand_object_mesh_generator.cc
OS X doesn't seem to have an appropriate copy of endian.h that includes
all the types used in OpenMesh. It does have endian.h (not on the default
include path), but not the types.
This fixes this issue by default searching for a system copy of endian.h
and if not found, using the manually added version.
The __has_include preprocessor directive requires gcc-5 or clang
> fix: _neuroglancer.so compiles on OS X without manual intervention

- python/test/layer_harness.py
- python/test/test_precomputed.py
- python/test/test_tasks.py
Moved from precomputed so that testing code can live in its own
space.
Also changed layer_delete to not ignore errors.
Added function create_storage in anticipation of additional tests being added.
**Testing Sufficiency Declaration**
Tests continue to pass.
> refactor: moved test layer creation/deletion to layer_harness

- python/neuroglancer/pipeline/task_queue.py
- python/neuroglancer/pipeline/threaded_queue.py
- python/test/test_taskqueue.py
- python/test/test_threadedqueue.py
It's becoming too difficult to synchronize the feature set of
Storage and TaskQueue. This refactors TaskQueue to use the new
ThreadedQueue base class in anticipation of refactoring Storage
as well.
This change also includes changing the exception handling in TaskQueue
to retry on HTTP 408 Timeout, 500 ISE, and 503 Service Unavilable.
It doesn't raise an exception but doesn't retry for HTTP 400 Bad Request
which typically indicates a task was deleted by another process.
All other exceptions are reraised.
**Possible Changes**
We might want to make `self._queue.put` a method of TaskQueue instead of exposing it to child classes.
**Testing Sufficiency Declaration**
Testing currently satisfies that insertions and deletions in the task queue, the only threaded operations, are not disrupted by …
> Creates ThreadedQueue base class and refactors TaskQueue

- python/neuroglancer/pipeline/storage.py
- python/neuroglancer/pipeline/task_creation.py
- python/neuroglancer/pipeline/tasks.py
- python/test/test_tasks.py
After running marching cubes, an additional file has to be
created which contains the list of chunks for every id.
We rely on sorting the keys to split the keys and parallelize 
this process.
> feat(MeshManifestTask) parallelizes mesh manifest creation.

- python/neuroglancer/pipeline/task_queue.py
When tag was set to '', it still activated that part of the API,
which then tried to group tasks by the empty tag.
> Tasks could not be leased

- python/ext/third_party/yacn/chunked_regiongraph/ChunkedGraphs.jl
- python/ext/third_party/yacn/chunked_regiongraph/constants.jl
- python/ext/third_party/yacn/chunked_regiongraph/graph_server.jl
- python/ext/third_party/yacn/chunked_regiongraph/prep.jl
- src/neuroglancer/object_graph_service.ts
The agglomerated segment ids the graph server generates are now transferred to Neuroglancer as UInt64. That should avoid duplicate labels until we have datasets with more than 32 bit "real" supervoxels.
Also a function has been added to retrieve the next level child segments for a given label.
> using graph servers full UInt64 vertex labels as mesh id

- python/neuroglancer/pipeline/scripts/compute_bounds.py
- python/neuroglancer/pipeline/scripts/generate_manifests.py
- python/neuroglancer/pipeline/scripts/ngmesh2obj.py
- python/neuroglancer/pipeline/scripts/remap2npy.py
- python/neuroglancer/pipeline/scripts/super_downsample.py
compute_bounds.py: given a layer, compute the bbox and chunk size so we can set info accurately
generate_manifests.py: generate manifests for a newly meshed object. Can also be done with tasks.
ngmesh2obj.py: convert a neuroglancer mesh into .obj representation. useful for sharing outside the lab.
remap2npy.py: convert an .h5 segmentation remap into a numpy representation used by the pipeline
super_downsample.py: for small volumes, you can superdownsample using this script, but it is generally supersceded by tasks.
Added documentation to scripts
> feat(scripts): created scripts directory and populated it

- python/ext/third_party/mc/_mesher.pyx
- python/ext/third_party/mc/cMesher.h
Ricardo Kirkner found that 'points', which should have been a float,
was instead an unsigned int. If the vertex position was ever negative,
which can happen near the edges of the volume, a large displacement would
appear.
This fix merely assigns the correct type to the python interface to the
c++ code.
Resolves #92
> fix(MeshTask): integer underflow causing large spikes in meshes

- python/neuroglancer/pipeline/storage.py
- python/neuroglancer/pipeline/task_creation.py
- python/neuroglancer/pipeline/tasks.py
- python/test/test_storage.py
- python/test/test_tasks.py
List files now is consistent across filesystem, google storage, and
amazon s3. It now returns the relative path from the layer path
rather than trying to fake some kind of flat directory unsuccessfully.
> fix(Storage): list_files consistent across services + flat option

- python/neuroglancer/pipeline/scripts/validate_provenance.py
- python/neuroglancer/pipeline/storage.py
- python/neuroglancer/pipeline/volumes/provenance.py
- python/requirements.txt
- python/test/test_provenance.py
- python/test/test_storage.py
As discussed in the pinky channel on slack:
so i was messing around with potential provenance data formats. What do you guys think of this proposal?
1. Every dataset (e.g. pinky40_v11) has a provenance file. The file describes:
```{
'dataset_name': '',
'dataset_description': '',
'organism': '',
'imaged_date': '',
'imaged_by': '',
'references': [], # e.g. dois, urls, titles
'owners': [], # e.g. email addresses
}
```
2. Every layer in the dataset has its own provenance file:
```{
'description': '',
'sources': [], # e.g. [ 'gs://neuroglancer/pinky40_v11/image' ]
'processing': [],
'uploaded_by': '',
}
```
The nice thing about these files is that we can check automatically for missing metadata and some of it can be generated automatically when we run the pipeline.
> Provenance Info + Validation Script

- python/neuroglancer/pipeline/storage.py
- python/test/test_storage.py
- Adds content_type to storage.put_file and storage.put_files
- Adds gzip support to FileInterface for storage. 
Previously, threads would often collide when executing
os.makedirs in the FileInterface. This made testing unreliable
as random failures could happen. This is fixed by handling
errors properly in lib.mkdir, which is now threadsafe and
accessible to all pipeline files. This replaces the locking
system that bottlenecks multithreaded processes.
Additionally, we've added support for setting the Content-Type
of put files.
Additionally, the FileInterface now supports compressed files
correctly allowing for uniform testing and transparent compressed
file storage.
> Add content_type to put_files and gzip support to Fileinterface

- python/ext/src/on_demand_object_mesh_generator.cc
Previously compiling with clang was working, since it supports
the __has_include directive. Adding some logic to pick the
right endian.h file on gcc which doesn't support that directive.
https://clang.llvm.org/docs/LanguageExtensions.html#langext-has-include
Resolves #128
> fix(mesher.so): compilation won't fail on gcc

- python/neuroglancer/downsample.py
- python/test/downsample_test.py
For layer types where the voxel value is a scalar activations (e.g. errors),
max pooling probably makes more sense.
Related to #88
> feat(downsample): added max pooling

- python/neuroglancer/pipeline/storage.py
- python/requirements.txt
Reduces number of requests by 2x for uploading meshes and segmentation.
> perf(Storage): gcloud content-encoding sent in 1 request instead of 2

- python/neuroglancer/pipeline/threaded_queue.py
There's a bug where it's possible for the main thread to proceed after
queue.join() stops blocking butbefore self.processed is incremented,
resulting in a temporary discrepancy of 1. We invert the order of these
operations to ensure that join will not stop blocking until all tasks
are accounted for.
> fix(ThreadedQueue): ensure processed matches task_done

- python/requirements.txt
see this issue:
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3736
if the version is not correct, will get error:
```
File "/Users/jpwu/libs/anaconda2/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 502, in download_as_string
self.download_to_file(string_buffer, client=client)
File "/Users/jpwu/libs/anaconda2/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 464, in download_to_file
self._do_download(transport, file_obj, download_url, headers)
File "/Users/jpwu/libs/anaconda2/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 418, in _do_download
download.consume(transport)
File "/Users/jpwu/libs/anaconda2/lib/python2.7/site-packages/google/resumable_media/requests/download.py", line 96, in consume
transport, method, url, …
```
> google-cloud 0.26 only works with google-cloud-storage version < 1.3.0

- appengine/queue/taskqueue.py
- appengine/queue/test.py
The timer thread was not started as a daemon, making a call
to lease with n seconds would take that same amount of time
to respond.
> fix(appengine/queue): lease api call waits for lease timer.

- .travis.yml
Looks like node 8 is a little more efficient (~7-10%) than node 6 (we're on node 7): 
https://hackernoon.com/upgrading-from-node-6-to-node-8-a-real-world-performance-comparison-3dfe1fbc92a3
> chore: upgrade to node 8.4.0

- .travis.yml
- was_modified.py
We make a list of all the files that has being changed
And we only test for the current changes.
The idea is that when we modify the frontend, that cannot
break anything in the backend.
So we only run frontend tests and deployments, which saves
time.
The drawback is that if something is brokend in the backend,
and we only modified the frontend. Travis will succed but
there will be still problems there. So we need to be extra
carefull that the base is correct.
To aliviate this problem we set up a daily cron job that
will build and deploy everyting.
> chore: reduce continuous integration time

- python/neuroglancer/pipeline/task_queue.py
- python/requirements.txt
Appearently we missed the np.ndarray serialization logic and
the tenacity requirement when merging the wms_bigbang.
> fix: missing library and logic from for working with queues

- python/neuroglancer/skeleton.py
- src/neuroglancer/datasource/brainmaps/frontend.ts
- src/neuroglancer/datasource/dvid/frontend.ts
- src/neuroglancer/datasource/ndstore/frontend.ts
- src/neuroglancer/datasource/nifti/frontend.ts
- src/neuroglancer/datasource/precomputed/backend.ts
- src/neuroglancer/datasource/precomputed/base.ts
- src/neuroglancer/datasource/precomputed/frontend.ts
- src/neuroglancer/datasource/python/frontend.ts
- src/neuroglancer/datasource/render/frontend.ts
- src/neuroglancer/segmentation_user_layer.ts
- src/neuroglancer/skeleton/frontend.ts
- src/neuroglancer/sliceview/volume/frontend.ts
Skeletons were supported by the python backend.
But not all the code necesary for doing so was available.
We were instead using the synapse layer to display skeletons
but the problem is that large skeletons were not able to be
displayed given the max lenght of an url.
Both solutions above required running a local server, the precomputed
datasource let us use s3 or gcs to serve large amounts of data directly,
but precomputed only supported images and meshes, it can now supporty
skeletons.
skeletons.py implements encoding for a very simple binary format for
skeletons, which is similar in nature to how meshes are saved.
We don't yet have any decoder implementation.
The neuroglancer frontend it's very flexible in how to display skeletons,
it allows you to store abitrary information for every …
> feat(skeletons): precomputed support for skeletons

- src/neuroglancer/state_server.ts
- src/neuroglancer/ui/url_hash_binding.ts
- src/neuroglancer/viewer.ts
Update neuroglancer frontend to handle a state server, with identical functionality as before `Upstream google` merge.
Append `stateServer` key to the neuroglancer URL's ending state JSON, and use the server URL as the  value.
> Fix state server

- src/neuroglancer/chunk_manager/backend.ts
- src/neuroglancer/chunked_graph/backend.ts
- src/neuroglancer/chunked_graph/base.ts
- src/neuroglancer/chunked_graph/frontend.ts
- src/neuroglancer/datasource/precomputed/backend.ts
- src/neuroglancer/datasource/precomputed/base.ts
- src/neuroglancer/datasource/precomputed/frontend.ts
- src/neuroglancer/gpu_hash/hash_table.ts
- src/neuroglancer/mesh/backend.ts
- src/neuroglancer/mesh/frontend.ts
- src/neuroglancer/segmentation_user_layer.ts
- src/neuroglancer/shared_disjoint_sets.ts
- src/neuroglancer/skeleton/backend.ts
- src/neuroglancer/skeleton/frontend.ts
- src/neuroglancer/sliceview/volume/frontend.ts
- src/neuroglancer/sliceview/volume/segmentation_renderlayer.ts
- src/neuroglancer/uint64_set.ts
- src/neuroglancer/util/disjoint_sets.ts
- src/neuroglancer/widget/segment_set_widget.ts
Calling the ChunkedGraph's getLeaves() function for visible chunks, only (instead of the whole dataset). Allows displaying huge objects without crashing the graphserver and/or neuroglancer.
TODO: Use bigger chunks when zooming out, only load "large" supervoxels
> Chunk based supervoxel loading from Chunked Graph

- src/neuroglancer/sliceview/base.ts
Fixes https://github.com/seung-lab/neuroglancer/issues/191
Changes the absolute values for `scaleIndex`, which influence the priority for sliceview chunks, to a normalized version. Meaning that the lowest-resolution MIP maps of each layer are always loaded simultaneously, independent on _how many_ MIP maps those layers consist of.
> feat(sliceview): normalize source weight

- src/main_python.ts
- src/neuroglancer/ui/default_viewer_setup.ts
- src/neuroglancer/ui/url_hash_binding.ts
- src/neuroglancer/viewer.ts
this provides link shortening capability to neuroglancer through a json state server, which we have currently deployed.  Note the default state server will only presently work at princeton and allen until we get authentication setup.
> json state server link shortener

- src/neuroglancer/segmentation_display_state/base.ts
- src/neuroglancer/segmentation_user_layer.ts
- src/neuroglancer/ui/layer_side_panel.css
- src/neuroglancer/widget/segment_set_widget.css
- src/neuroglancer/widget/segment_set_widget.ts
Added two buttons to side panel to add ability for user to: (1) hide a
segment from the display without removing it from the side panel, and (2)
copy a segment ID to the clipboard.
Made the assumption that hidden segments should be known to the side
panel, and not stored in the URL, which may or may not be correct/best.
Edit: Pushed new commit that fixes bug @nkemnitz pointed out to me
> Ability to hide selected segments & to copy segment IDs

- src/neuroglancer/chunk_manager/base.ts
- src/neuroglancer/mesh/backend.ts
- src/neuroglancer/mesh/frontend.ts
- src/neuroglancer/segmentation_display_state/base.ts
- src/neuroglancer/segmentation_user_layer.ts
- src/neuroglancer/skeleton/backend.ts
- src/neuroglancer/skeleton/frontend.ts
Now that the graph server always returns the mesh manifest files including only existing meshes, we don't have to play ping-pong between Neuroglancer, GCS and the graph server anymore to recursively load missing meshes.
Makes mesh loading a bit more predictable / easier to follow, and we don't have to carry around the graph server within the mesh and skeleton backend.
Also found some bugs related to rootSegment <-> visibleSegment3D. Most of the time they refer to the same segments. Except for when users play with segment equivalences in a non-graph-server dataset.
> refactor(chunked_graph/mesh): remove recursive missing mesh loading

- src/neuroglancer/overlay.ts
Resolves #259 
Simple fix - adding a listener to the overlay div directly, since the framework removes the div when overlay is closed there won't be any leaks. I feel anything more would be an overkill at this time.
> overlay click event listener

- src/neuroglancer/overlay.ts
When mouse click starts inside the overlay and ends outside (for eg. select all in state editor), it is unexpectedly closed. Using mousedown in place of click event avoids that.
> change mouse action

- src/neuroglancer/layer_specification.ts
Not a fan of this, but it makes existing links that are floating around work with the new `segmentation_user_layer_with_graph`.
Hopefully we can keep this a temporary change...
> compat(graphene): force upgrade to segmentation_with_graph

- src/neuroglancer/annotation/user_layer.ts
- src/neuroglancer/image_user_layer.ts
- src/neuroglancer/segmentation_user_layer.ts
- src/neuroglancer/single_mesh_user_layer.ts
- src/neuroglancer/ui/annotations.css
- src/neuroglancer/ui/annotations.ts
- src/neuroglancer/ui/graph.css
- src/neuroglancer/ui/graph_multicut.ts
- src/neuroglancer/vector_graphics_user_layer.ts
- src/neuroglancer/widget/minimizable_group.css
- src/neuroglancer/widget/minimizable_group.ts
- src/neuroglancer/widget/segment_set_widget.css
- src/neuroglancer/widget/tab_view.css
Introduces a "minimizable group" container, that allows to
* group widgets into submenus
* hide groups
* allows to mark widgets as rigid/important or scrollable/shrinkable
> Flexible group widgets for cluttered user layers

- src/neuroglancer/segmentation_user_layer.ts
- src/neuroglancer/segmentation_user_layer_with_graph.ts
- tsconfig.json
- fixes an issue where a Uint64[][] got accidentally passed to the hashmap, resulting in endless rehashing attempts
- rework `two-point merge`, `merge-selected` and `cut-selected` for `SegmentationUserLayer`.
- Only group representatives will be shown in the segment selection
- Merging and splitting correctly updates `visibleSegments2D`, `visibleSegments3D` and `rootSegments`
- Added `"lib": ["dom", "dom.iterable", "es2017", "esnext"]` to use fancy esnext `Array.flatMap`
> Fix: Correctly set up 2D, 3D and root segments when merging/cutting without graph

- src/neuroglancer/segmentation_user_layer.ts
When the initially selected layer is not the segmentation layer with the omni widget, the widget never loads. This commit fixes that.
> Fix: add omni segment widget when layer is not initially selected

- src/neuroglancer/segmentation_user_layer_with_graph.ts
- src/neuroglancer/sliceview/chunked_graph/backend.ts
- src/neuroglancer/sliceview/chunked_graph/base.ts
- src/neuroglancer/sliceview/chunked_graph/frontend.ts
SegmentationUserLayerWithGraph's ChunkedGraphSource never updated its version of rootSegments after restoreState, causing incorrect leaves requests to the ChunkedGraph on the backend
> Fix: after restoreState, CG Segmentation user layer's source had old version of rootSegments

- src/neuroglancer/datasource/index.ts
- src/neuroglancer/datasource/precomputed/frontend.ts
This PR adds support for a new key `redirect` to the precomputed info file. If specified, it will work as an automatic layer source redirection. This is useful in order to forward users who use old, bookmarked links to newer versions / formats of the specified layer.
Throws an error if more than 10 redirects occur, or a cycle is detected.
Works for loading existing links, as well as when trying to add layers via the layer dialog.
> feat(datasource/precomputed): Layer redirection support

- src/neuroglancer/segmentation_user_layer_with_graph.ts
The `CHUNKED_GRAPH_JSON_KEY` allowed users to set their own chunked graph for a layer (mostly for debugging), but if not manually specified it was read from the layer location and written to the JSON state. From there, links spread out to users and now everyone uses links with old graph server locations...
Luckily, the feature isn't used much / at all, so we might as well remove it.
> fix(graphene): Retire CHUNKED_GRAPH_JSON_KEY

- python/neuroglancer/viewer_state.py
- src/neuroglancer/segmentation_user_layer.ts
- src/neuroglancer/segmentation_user_layer_with_graph.ts
- src/neuroglancer/sliceview/volume/segmentation_renderlayer.ts
Adds a checkbox to the "Segment Selection" section which, when selected, disables the ability to double-click to select/deselect a segment.
> Add checkbox to ignore layer segment interactions

- WHATS_NEW.md
- src/neuroglancer/graph/graph_operation_layer_state.ts
- src/neuroglancer/segmentation_user_layer_with_graph.ts
- src/neuroglancer/sliceview/chunked_graph/frontend.ts
- src/neuroglancer/sliceview/volume/segmentation_renderlayer.ts
- src/neuroglancer/sliceview/volume/supervoxel_renderlayer.ts
- src/neuroglancer/status.ts
- src/neuroglancer/ui/graph_multicut.ts
A new "crystal ball" button in the multicut group performs a split preview. It hits the split_preview endpoint in the ChunkedGraph, which calculates the mincut given the sources and sinks but does not actually update the graph. The CG returns the connected components of supervoxels in the region around the cut, assuming the split were to take place. This is displayed to the user as groups of red and blue supervoxels. 
Note: for this PR to work the associated ChunkedGraph PR, https://github.com/seung-lab/PyChunkedGraph/pull/162, has to be online.
> feat: Split preview for multicut

- WHATS_NEW.md
- src/neuroglancer/segmentation_user_layer.ts
Under 3D Visualization, uncheck "Load layer meshes (requires refresh)" then refresh the page to stop that mesh's layers from being loaded. The same option exists for skeletons.
Fixes https://github.com/seung-lab/neuroglancer/issues/295.
> Options to not load meshes/skeletons for single layers

- WHATS_NEW.md
- src/neuroglancer/util/automatic_focus.ts
- src/neuroglancer/widget/coordinate_transform.ts
- src/neuroglancer/widget/position_widget.ts
- src/neuroglancer/widget/shader_code_widget.ts
Previously when moving the mouse off of the coordinates (position widget) at the top, it would lose focus (so you had to hold your mouse there while editing it). With this change, you can move your mouse elsewhere, and only when you click on another panel will the coordinates get deselected.
Partially addresses https://github.com/seung-lab/neuroglancer/issues/361.
> Don't lose focus when moving mouse off coordinates

- WHATS_NEW.md
- src/neuroglancer/annotation/index.ts
- src/neuroglancer/graph/path_finder_state.ts
- src/neuroglancer/segmentation_user_layer_with_graph.ts
- src/neuroglancer/sliceview/chunked_graph/frontend.ts
- src/neuroglancer/ui/graph_multicut.ts
- src/neuroglancer/widget/find_path_widget.css
- src/neuroglancer/widget/find_path_widget.ts
This PR allows users to find paths between two different locations in a segment for graphene segmentation layers. It is useful to detect locations of mergers. It adds a widget to the graph tab by which the user puts down two points on a segment in either 2D or 3D. Neuroglancer then sends a request to the ChunkedGraph which returns a list of 3D coordinates that make up a path between the two locations in the segment. This path is displayed as line segment annotations.
Edit: Relevant ChunkedGraph PR is now live.
> Feat (graphene): Path Finding Widget

- src/neuroglancer/datasource/graphene/frontend.ts
- src/neuroglancer/datasource/precomputed/frontend.ts
Currently, neuroglancer treats missing mesh info files as legacy
format, but we found that it is necessary to add some attributes
to mesh info files in order to deduplicate chunk boundaries. However,
this leaves us with no way to read legacy formats. Thus, we add
neuroglancer_legacy_mesh as an explicit type to enable continued use.
> fix: add 'neuroglancer_legacy_mesh' as an explicit mesh info type

- src/neuroglancer/authentication/auth_redirect.html
- src/neuroglancer/authentication/backend.ts
- src/neuroglancer/authentication/base.ts
- src/neuroglancer/authentication/frontend.ts
- src/neuroglancer/datasource/graphene/backend.ts
- src/neuroglancer/datasource/graphene/frontend.ts
Example layer:
`graphene://https://minniev1.microns-daf.com/proxy/fly_em`
Also switched from using token in header to token in query param to avoid having to send an options request though this does mean that tokens are likely to leak in server access logs.
> Feat: Supporting authenticated em layer identified by graphene

- src/neuroglancer/authentication/backend.ts
- src/neuroglancer/authentication/base.ts
- src/neuroglancer/authentication/frontend.ts
- src/neuroglancer/datasource/graphene/backend.ts
- src/neuroglancer/sliceview/chunked_graph/frontend.ts
broken by recent change to make authFetch conform to fetchOk behavior.
> Fix: Made checking response.ok optional in authFetch so chunked graph operations can correctly handle the errors

- src/neuroglancer/layer.ts
Undo button sticks around for 15 seconds, up from 10
> Extend period deleting layer can be undone

- src/index.html
- src/neuroglancer/preferences/user_preferences.ts
- src/neuroglancer/save_state/save_state.css
- src/neuroglancer/save_state/save_state.ts
- src/neuroglancer/viewer.ts
addresses #433 
replaced storageAvailable with storageAccessible, which only returns false if localStorage has been disabled
Share Button is disabled when state server push is made from Share Button or Share Button from Warning Status Message. This matches the behavior of pressing the "Post State to State Server" button.
Adds Clear States and Clear Storage buttons, the former purges all existing states, while the later completely clears local storage entirely and triggers a reload.
Local Storage is tied to domain so this only affects Neuroglancer
Share button should only highlight when the state has actually changed and not been shared
history only keeps most recent 100 entries, after which it starts deleting old ones, additionally save history can trigger LRU eviction if it LocalStorage …
> better storage management, manual storage control

- src/neuroglancer/sliceview/chunked_graph/frontend.ts
- src/neuroglancer/widget/find_path_widget.css
- src/neuroglancer/widget/find_path_widget.ts
High precision is default behavior, but mesh downloading takes a long time with new sharded mesh format. Add rough lower precision option that doesn't require mesh download.
> add precision mode checkbox to find path widget

- src/neuroglancer/sliceview/volume/segmentation_renderlayer.ts
The multicut darkens the segments around that are not the one being cut. However it does not do so for segment 0; this PR fixes this. 
See: #468
> Fix: Multicut blackout segment 0

- src/neuroglancer/layer_panel.css
- src/neuroglancer/layer_panel.ts
Create a span to fix the size of the layer bar item. This fixes the problem of hovering over a segment/supervoxel and having the view change as all the layer items shift over (see: #450). The user can no longer see the full segment ID in the layer bar item however.
> Fix size of layer item

- src/neuroglancer/widget/segment_set_widget.css
Our current minimizable group styling has been broken by the latest Chrome update. Currently, overflow causes the segment set widget to become tiny and hard to use. Workaround: set a max vh for the widget until we fix the group styling.
> Fix: fix max height of segment set widget to prevent overflow

- src/neuroglancer/annotation/annotation_layer_state.ts
- src/neuroglancer/annotation/annotation_layer_view.ts
- src/neuroglancer/annotation/user_layer.ts
- src/neuroglancer/segmentation_user_layer_with_graph.ts
- src/neuroglancer/ui/annotations.ts
- src/neuroglancer/viewer.ts
This PR addresses issues #425 and #432 by adding a checkbox to annotation layers that, when checked, will display any associated segments of an annotation when that annotation is selected. It also saves this new checkbox and the "bracket shortcuts show segmentation" checkboxes in the state as requested.
> Add checkbox for annotation selection displaying segmentation

- src/index.html
- src/neuroglancer/webgl/context.ts
A StatusMessage already appears at the bottom when there is no WebGL2 support, but an alert message is much clearer and more explicit. See: #443
> Alert user when no WebGL2

- WHATS_NEW.md
- src/neuroglancer/datasource/graphene/backend.ts
- src/neuroglancer/datasource/graphene/base.ts
- src/neuroglancer/segmentation_user_layer_with_graph.ts
- src/neuroglancer/sliceview/chunked_graph/frontend.ts
- src/neuroglancer/ui/default_input_event_bindings.ts
- src/neuroglancer/viewer.ts
Adds a new shortcut to trigger mesh manifest call and re-render mesh after a merge/split.
This helps avoid refreshing the page to check the new mesh.
`Ctrl+Shift+mousedown0` on an active segment in 2D/3D views to trigger the action.
> shortcut to reload mesh

- src/neuroglancer/differ/differ.ts
- src/neuroglancer/segmentation_user_layer.ts
- src/neuroglancer/segmentation_user_layer_with_graph.ts
- src/neuroglancer/ui/graph_multicut.ts
- src/neuroglancer/viewer.ts
Undo/Redo has erroneous behavior when state changes include an edit. This patch temporarily disables undo/redo in merge or split mode and when making a multicut. Additionally, undo/redo history before an edit is made is discarded to prevent returning to an outdated state.
> disable undo/redo when making edits

- src/neuroglancer/viewer.ts
Addresses #552 by showing the save dialog when the user attempts the `save-state-getjson` shortcut when there is no state server for the session. Also fixes a bug where if you request to copy the raw url via the `save-state-getraw` shortcut without a state server in the session, neuroglancer does not and tells the user there is no state server.
> Show save dialog when no state server

- package-lock.json
- src/neuroglancer/datasource/graphene/backend.ts
- src/neuroglancer/datasource/graphene/frontend.ts
- src/neuroglancer/sliceview/chunked_graph/backend.ts
Leverage the new ChunkedGraph many_leaves endpoints to request the leaves of all selected roots in layer at once (per current viewport chunk). This will greatly reduce the load on the ChunkedGraph server from users who select many roots in their sessions, as right now one request for leaves is made per root per current viewport chunk. It should also be smoother for the user. I stress tested with >8000 selected roots with no issues.
Note that the code change is obscured behind formatting changes. I reformatted the changed files using clang-format and this changed the files more than I anticipated. The main changes are to `download` in `src/neuroglancer/datasource/graphene/backend.ts` lines 256-275 and to the `decodeSupervoxelArray` function.
> Feat(graphene): Request leaves of all selected roots at once

- src/neuroglancer/util/http_request.ts
Currently needed for graphene layers to retrieve cloudian data, as the ChunkedGraph returns matrix paths to Neuroglancer.
> feat: Enable matrix protocol for cloudian

- src/neuroglancer/save_state/save_state.ts
This PR restores communication between Neuroglancer and python state server. Python state server links have an additional path (e.g. `/v/f6ab55bea753e35d7d518c5da22b40a78532047e`), which was ignored during the local ID generation.
> fix(save_state): restore compatibility with python state server

- src/neuroglancer/sliceview/chunked_graph/frontend.ts
Find path tool currently sends supervoxel ids when points are selected in 2D which the ChunkedGraph does not expect. Neuroglancer should send root ids instead.
> Fix: find path in 2D

- src/neuroglancer/graph/graph_operation_layer_state.ts
- src/neuroglancer/segmentation_user_layer_with_graph.ts
- src/neuroglancer/ui/default_input_event_bindings.ts
- src/neuroglancer/ui/graph_multicut.ts
- src/neuroglancer/ui/tool.ts
- src/neuroglancer/viewer.ts
- src/neuroglancer/widget/annotation_tool_status.ts
This PR addresses issues #537 and #519 by introducing ctrl+shift+backslash as a way to enable the multicut tool or to switch between multicut groups. Currently the only way of doing so is to manually go to the Rendering tab of a graphene layer, and click on the relevant buttons. The PR also changes the tool description in the top right to show users which group is currently active, and changes the description color depending on the group for more visibility.
> Feat: shortcut for multicut to improve usability

- src/neuroglancer/segmentation_user_layer_with_graph.ts
- src/neuroglancer/ui/default_input_event_bindings.ts
- src/neuroglancer/viewer.ts
This PR changes the `switch-multi-group` hotkey to `g` and adds two new hotkeys for increase and decreasing segmentation opacity by 10% to `i` and `u`, respectively.
> Neuvue Feat: Multicut and Mesh Opacity Hotkeys

- src/neuroglancer/graph/path_finder_state.ts
- src/neuroglancer/widget/find_path_widget.ts
If a path already exists, and the user clicks "Generate Path", the `getLatestSegments()` function will reset the source and target points to have the latest root IDs and attempt to regenerate the path. 
This also sets the path finding precision mode to be checked by default.
> Neuvue Feat: Allow path to be regenerated with new root IDs

- src/neuroglancer/widget/segment_set_widget.ts
now retrieves its segment id from the html data attribute rather than the textContent, to allow for renaming segments
resolves https://github.com/seung-lab/neuroglancer/issues/600
> fix(segment_widget) changed how segment id is retrieved

- src/neuroglancer/annotation/annotation_layer_view.ts
- src/neuroglancer/save_state/save_state.ts
- src/neuroglancer/user_report/user_report.ts
- src/neuroglancer/util/br.ts
* this allows importCSV to utilize segment selection
* update to allow any case types and allow coordinates w/o brackets
> this allows importCSV to utilize segment selection (#612)
